FROM us-central1-docker.pkg.dev/genuine-flight-317411/devel/krr:v1.8.3

USER root
WORKDIR /finops

RUN python3 -m venv /finops/finops_venv

COPY requirementskrr.txt .

RUN /finops/finops_venv/bin/pip install --upgrade pip
RUN /finops/finops_venv/bin/pip install --no-cache-dir -r requirementskrr.txt

COPY . .

ENTRYPOINT ["/finops/finops_venv/bin/python", "run_krr.py"]