#Example of secrets.yaml file for helm
#This file isn't protected by .gitignore, don't fill in real values here.

db:
  password: "DB_PASSWORD"

rabbitmq:
  password: "RABBITMQ PASSWORD"

azure:
  subscription_id: ""
  client_id: ""
  client_secret: ""
  tenant_id: ""

aws:
  access_key_id: ""
  secret_access_key: ""

kube:
  # File path inside Helm chart.
  kubeconfigfile: "kubeconfigs/my-kube-config.yaml"