---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-loader
  namespace: {{ .Release.Namespace }}
  labels:
    department: monitor
    app: db-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-loader
  template:
    metadata:
      labels:
        app: db-loader
    spec:
      initContainers:
      - name: wait-for-rmq
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo "Waiting for RabbitMQ"; sleep 2; done;']
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"
      - name: wait-for-db
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z timescaledb 5432; do echo "Waiting for TimescaleDB"; sleep 2; done;']
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"

      containers:
      - name: loader
        image: {{ .Values.image.repository }}/finops-data-collector:{{ .Values.image.tag }}
        command: ["python3", "run_policies.py", "loader"]
        envFrom:
        - secretRef:
            name: app-env-vars
        - secretRef:
            name: rmq-env-vars
        resources:
          requests:
            cpu: "50m"
            memory: "150Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"