# Generated secrets for deploying the FinOps application.

# PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: app-env-vars
type: Opaque
data:
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  DB_NAME: {{ .Values.db.name | b64enc | quote }}

---
# RabbitMQ
apiVersion: v1
kind: Secret
metadata:
  name: rmq-env-vars
type: Opaque
data:
  RMQ_USER: {{ .Values.rabbitmq.user | b64enc | quote }}
  RMQ_PASSWORD: {{ .Values.rabbitmq.password | b64enc | quote }}
  RMQ_HOST: {{ .Values.rabbitmq.host | b64enc | quote }}
  RMQ_PORT: {{ .Values.rabbitmq.port | toString | b64enc | quote }}

---
# Azure
apiVersion: v1
kind: Secret
metadata:
  name: azure-personal-env-vars
type: Opaque
data:
  AZURE_SUBSCRIPTION_ID: {{ .Values.azure.subscription_id | b64enc | quote }}
  AZURE_CLIENT_ID: {{ .Values.azure.client_id | b64enc | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.azure.client_secret | b64enc | quote }}
  AZURE_TENANT_ID: {{ .Values.azure.tenant_id | b64enc | quote }}

---
# AWS
apiVersion: v1
kind: Secret
metadata:
  name: aws-env-vars
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.access_key_id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret_access_key | b64enc | quote }}

---
# Web App
apiVersion: v1
kind: Secret
metadata:
  name: web-env-vars
type: Opaque
data:
  ENABLE_METRICS: {{ .Values.web.metrics | toString | b64enc | quote }}
  ENABLE_COSTS: {{ .Values.web.costs | toString | b64enc | quote }}

---
# Config files worker1
# Reads the whole conf directory and creates a secret from it
apiVersion: v1
kind: Secret
metadata:
  name: conf-files-worker1
type: Opaque
data:
  {{- range $path, $bytes := .Files.Glob "conf/*" }}
  {{ base $path }}: {{ $bytes | b64enc }}
  {{- end }}

# Kubeconfig (Generated only if kubeconfigfile is filled in values)
{{- if .Values.kube.kubeconfigfile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: external-kubeconfig
type: Opaque
data:
  config: {{ .Files.Get .Values.kube.kubeconfigfile | b64enc }}
{{- end }}