name: Python Tests

on:
  push:
    branches: [ "main" ]

# based on https://realpython.com/github-actions-python/
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r data_collector/requirements.txt
        pip install -r data_collector/requirements-tests.txt
        pip install -r webapp/requirements.txt
        pip install -r webapp/requirements-tests.txt

    - name: Run Data Collector Pytest
      env:
        PYTHONPATH: ${{ github.workspace }}/data_collector
      run: |
        python -m pytest data_collector/tests/
    - name: Run Webapp Pytest
      env:
        PYTHONPATH: ${{ github.workspace }}/webapp
      run: |
        python -m pytest webapp/tests/